version: 0.2
os: linux

files:
  - source: SampleMavenTomcatApp.war
    destination: /opt/tomcat9/webapps/ROOT
    overwrite: yes
  - source: scripts/configure_http_port.xsl
    destination: /opt/tomcat9/scripts/

hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_application
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh
